project:
  type: website
  output-dir: _site

website:
  title: "Martini CG Force-field"
  image: "images/martini.gif"
  favicon: "images/favicon.png"
  # google-analytics: "G-"    # TODO: Pass Google Tag measurement Id.
  open-graph: true
  twitter-card: true
  site-url: http://cgmartini.nl
  repo-url: https://github.com/Martini-Force-Field-Initiative
  page-navigation: true
  search:
    type: overlay
    # algolia:   #TODO: take a look at Algolia searching engine and how to use it
    #   index-name: prod_QUARTO
    #   application-id: ZPJB5I1QN7
    #   search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
    #   analytics-events: true
    #   show-logo: true
  page-footer:
    # left: |
    #   Made with love and [Quarto](https://quarto.org).
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com  # TBA
        aria-label: Martini Twitter
      - icon: github
        href: https://github.com/Martini-Force-Field-Initiative
        aria-label: Martini GitHub
      # - icon: rss
      #   href: TBA
      #   aria-label: Martini Blog RSS        
  navbar:
    background: "#fdfffc" 
    logo: images/martini.gif
    logo-alt: "martini logo."
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "News"
        href: docs/blog/index.qmd
      - text: "About"
        href: about.qmd
      - text: "Downloads"
        href: docs/downloads/index.qmd
      - text: "Tutorials"
        href: docs/tutorials/index.qmd
      - text: "Discussions"
        href: docs/tutorials/index.qmd
      - text: "Publications"
        href: docs/publications/index.qmd
      - text: "Contact"
        href: docs/contact.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/Martini-Force-Field-Initiative" #TODO: open general repo for issues
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/Martini-Force-Field-Initiative"  #TODO: change this to discussions
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
    tools:
      - icon: twitter
        href: https://twitter.com  # TBA
        text: Martini Twitter
      - icon: github
        href: https://github.com/Martini-Force-Field-Initiative
        text: Martini GitHub
      # - icon: rss
      #   href: # TBA
      #   text: Martini Blog RSS        

  sidebar:
    - id: blog
      title: "Blog"

    - id: about
      title: "About"

    - id: downloads
      title: "Downloads"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: <b>Download categories</b><hr>
        - section: "Force field parameters"
          contents:
            - docs/downloads/force-field-parameters/particle-definitions.qmd
            - docs/downloads/force-field-parameters/input-parameters.qmd
            - docs/downloads/force-field-parameters/general-topology.qmd
            - docs/downloads/force-field-parameters/aminoacids.qmd
            - docs/downloads/force-field-parameters/solvents.qmd
            - docs/downloads/force-field-parameters/ions.qmd
            - docs/downloads/force-field-parameters/sugars.qmd
            - docs/downloads/force-field-parameters/polymers.qmd
            - docs/downloads/force-field-parameters/others.qmd
            - docs/downloads/force-field-parameters/dry-martini.qmd
            - docs/downloads/force-field-parameters/dna.qmd
            - docs/downloads/force-field-parameters/rna.qmd
            - docs/downloads/force-field-parameters/lipids.qmd
        - section: "Example applications"
          contents:
            - docs/downloads/example-applications/solvent-systems.qmd           
            - docs/downloads/example-applications/lipid-membranes.qmd
            - docs/downloads/example-applications/lipid-vesicles.qmd
            - docs/downloads/example-applications/micelles.qmd
            - docs/downloads/example-applications/multiscaling.qmd
            - docs/downloads/example-applications/peptides.qmd
            - docs/downloads/example-applications/polymers.qmd
            - docs/downloads/example-applications/other-systems.qmd
        - section: "Tools"
          contents: 
            - docs/downloads/tools/proteins-and-bilayers.qmd
            - docs/downloads/tools/resolution-transformation.qmd
            - docs/downloads/tools/visualization.qmd
            - docs/downloads/tools/other-tools.qmd
        - text: "Lectures"
          href: docs/downloads/lectures/index.qmd
    - id: tutorials
      title: "Tutorials"
      style: "floating"
      collapse-level: 1
      align: left
      contents: 
        - text: <b>Tutorials</b><hr>
        - section: "Martini 3 Tutorials"
          href: docs/tutorials/martini3/index.qmd
          contents: 
            - docs/tutorials/martini3/small_molecule_binding.qmd
            - docs/tutorials/martini3/parameterizing_small_molecule.qmd
        - section: "Martini 2 Tutorials"
          href: docs/tutorials/martini2/index.qmd
          contents:
            - docs/tutorials/martini2/lipids_and_lipidome.qmd
            - docs/tutorials/martini2/polymers.qmd
            - docs/tutorials/martini2/hybrid_models.qmd
            - docs/tutorials/martini2/parametrizing.qmd
            - docs/tutorials/martini2/high_throughput.qmd
            - docs/tutorials/martini2/proteins.qmd
            - docs/tutorials/martini2/rna.qmd
            - docs/tutorials/martini2/dna.qmd
            - docs/tutorials/martini2/visualizing_martini.qmd
            - docs/tutorials/martini2/others.qmd
            - docs/tutorials/martini2/free_energy.qmd
            - docs/tutorials/martini2/metadynamics.qmd
            - docs/tutorials/martini2/physisorption.qmd
        - text: "Martini workshops"
          href: docs/tutorials/martini/index.qmd
        - text: "2021 Martini online workshop"
          href: docs/tutorials/workshop2021/index.qmd
          contents: 
            - docs/tutorials/workshop2021/lectures.qmd
            - docs/tutorials/workshop2021/tutorials.qmd
    - id: publications
      title: "Publications"
      style: "floating"
      collapse-level: 2
      align: left
      contents: 
        - text: <b>Publications by year</b><hr>
        - docs/publications/2023.qmd
        - docs/publications/2022.qmd
        - docs/publications/2021.qmd
        - docs/publications/2020.qmd
        - docs/publications/2019.qmd
        - docs/publications/2018.qmd
        - docs/publications/2017.qmd
        - docs/publications/2016.qmd
        - docs/publications/2015.qmd
        - docs/publications/2014.qmd
        - docs/publications/2013.qmd
        - docs/publications/2012.qmd
        - docs/publications/2011.qmd
        - docs/publications/2010.qmd
        - docs/publications/2009.qmd
        - docs/publications/2008.qmd
        - docs/publications/2007.qmd
        - docs/publications/2006.qmd
        - docs/publications/2005.qmd
        - docs/publications/2004.qmd
        - docs/publications/2003.qmd
          
          

bibliography: references.bib

format:
  html:
    toc: true
    theme: 
      light: [default, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


filters:
  - filters/tools-tabset.lua


freeze: true

editor: visual

profile:
  group: 
    - [prerelease,rc]
