project:
  type: website
  output-dir: _site

website:
  title: "Martini CG Force-field"
  image: "images/martini.gif"
  favicon: "images/favicon.png"
  open-graph: true
  twitter-card: true
  site-url: http://cgmartini.nl
  repo-url: https://github.com/Martini-Force-Field-Initiative
  page-navigation: true
  search:
    type: overlay

  page-footer:
    background: "#fdfffc"
    left: 
      - text: <div class="footer-left"></div>
    center:
      - icon: twitter
        href: https://x.com/cg_martini
        aria-label: Martini Twitter
      - icon: github
        href: https://github.com/Martini-Force-Field-Initiative
        aria-label: Martini GitHub
      - icon: "question-circle"
        href: https://github.com/orgs/Martini-Force-Field-Initiative/discussions/categories/q-a
        aria-label: Ask a Question
    right: 
      - text: <div class="footer-right">Maintained by the Martini Developers Team <img src="https://martini-library.s3.us-east-2.amazonaws.com/icon.png" alt="Icon"> </div>
   

  navbar:
    background: "#fdfffc"
    logo: images/martini.gif
    logo-alt: "martini logo."
    title: false
    collapse-below: lg
    left:

      - text: "Home"
        icon: house-fill
        href: index.qmd

      - text: "Tutorials"
        icon: mortarboard-fill 
        href: docs/tutorials/index.qmd

      - text: "{{< fa solid meteor >}} Downloads"
        href: docs/downloads/index.qmd

      - text: "{{< fa solid newspaper >}} Publications"
        href: docs/publications/index.qmd

      - text: "{{< fa solid bullhorn >}} Announcements"
        href: docs/blog/index.qmd

      - text: "{{< fa regular address-book >}} Contact"
        href: docs/contact.qmd

      - text: "{{< fa solid circle-info >}}Help"
        menu:
          - text: "Discussion Board"
            icon: "chat-right-text"
            href: "https://github.com/orgs/Martini-Force-Field-Initiative/discussions"
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/orgs/Martini-Force-Field-Initiative/discussions" 
          - text: "Ask a Question"
            icon: "question-circle"
            href: "https://github.com/orgs/Martini-Force-Field-Initiative/discussions/categories/q-a"
    
    tools:
      - icon: twitter
        href: https://x.com/cg_martini
        text: Martini Twitter
      - icon: github
        href: https://github.com/Martini-Force-Field-Initiative
        text: Martini GitHub

  sidebar:

    - id: tutorials
      title: "Tutorials"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: <b>Summary</b><hr>
          href: docs/tutorials/index.qmd
        - text: "🎓 Martini Lectures"
          href: docs/tutorials/Martini3/lectures.qmd
        - text: "🛠️ Hands-on Tutorials"
          href: docs/tutorials/Martini3/tutorials.qmd
        - text: "🕸️ Legacy Material"
          href: docs/tutorials/Legacy/index.qmd

    - id: downloads
      title: "Downloads"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: <b>Summary</b><hr>
          href: docs/downloads/index.qmd
        - section: "🫧 Force field parameters"
          contents:
            - section: <i class="fa-solid fa-dice-three"></i> Martini 3
              contents:
                - docs/downloads/force-field-parameters/martini3/particle-definitions.qmd
                - docs/downloads/force-field-parameters/martini3/aminoacids.qmd
                - docs/downloads/force-field-parameters/martini3/lipidome.qmd
                - docs/downloads/force-field-parameters/martini3/nucleic_acids.qmd
                - docs/downloads/force-field-parameters/martini3/carbohydrates.qmd
                - docs/downloads/force-field-parameters/martini3/polymers.qmd
                - docs/downloads/force-field-parameters/martini3/solvents.qmd
                - docs/downloads/force-field-parameters/martini3/ions.qmd
            - section: <i class="fa-solid fa-dice-two"></i> Martini 2
              contents:
                - docs/downloads/force-field-parameters/martini2/particle-definitions.qmd
                - docs/downloads/force-field-parameters/martini2/aminoacids.qmd
                - docs/downloads/force-field-parameters/martini2/lipidome.qmd
                - docs/downloads/force-field-parameters/martini2/nucleic_acids.qmd
                - docs/downloads/force-field-parameters/martini2/carbohydrates.qmd
                - docs/downloads/force-field-parameters/martini2/polymers.qmd
                - docs/downloads/force-field-parameters/martini2/solvents.qmd
                - docs/downloads/force-field-parameters/martini2/ions.qmd
                - docs/downloads/force-field-parameters/martini2/others.qmd
                - docs/downloads/force-field-parameters/martini2/dry-martini.qmd
        - section: "🗄 Example input files"
          contents:
            - docs/downloads/example-input-files/general-topology.qmd
            - docs/downloads/example-input-files/md-parameters.qmd
        - section: "🧑‍💻️ Example applications"
          contents:
            - docs/downloads/example-applications/solvent-systems.qmd
            - docs/downloads/example-applications/lipid-membranes.qmd
            - docs/downloads/example-applications/lipid-vesicles.qmd
            - docs/downloads/example-applications/micelles.qmd
            - docs/downloads/example-applications/multiscaling.qmd
            - docs/downloads/example-applications/peptides.qmd
            - docs/downloads/example-applications/polymers.qmd
            - docs/downloads/example-applications/other-systems.qmd
        - section: "⚒️ Tools"
          contents:
            - docs/downloads/tools/proteins-and-bilayers.qmd
            - docs/downloads/tools/resolution-transformation.qmd
            - docs/downloads/tools/visualization.qmd
            - docs/downloads/tools/other-tools.qmd

    - id: publications
      title: "Publications"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: <b>Publications by year</b><hr>
        - docs/publications/2023.qmd
        - docs/publications/2022.qmd
        - docs/publications/2021.qmd
        - docs/publications/2020.qmd
        - docs/publications/2019.qmd
        - docs/publications/2018.qmd
        - docs/publications/2017.qmd
        - docs/publications/2016.qmd
        - docs/publications/2015.qmd
        - docs/publications/2014.qmd
        - docs/publications/2013.qmd
        - docs/publications/2012.qmd
        - docs/publications/2011.qmd
        - docs/publications/2010.qmd
        - docs/publications/2009.qmd
        - docs/publications/2008.qmd
        - docs/publications/2007.qmd
        - docs/publications/2006.qmd
        - docs/publications/2005.qmd
        - docs/publications/2004.qmd
        - docs/publications/2003.qmd

    - id: blog
      title: "Announcements"
      
    - id: contact
      title: "Contact"

format:
  html:
    toc: true
    theme:
      light: [default, cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: 
      - file: random-quotes.html 
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
      - file: random-quotes.html 

freeze: true

editor: visual

profile:
  group:
    - [prerelease,rc]
